# Exceptions: The failwith Function (F#)

The **failwith** function generates an F# exception.


## CAPS_SYNTAX_MD

```
failwith error-message-string
```

## CAPS_REMARKS_MD
The *error-message-string* in the previous syntax is a literal string or a value of type **string**. It becomes the **Message** property of the exception.

The exception that is generated by **failwith** is a **Microsoft.FSharp.Core.FailureException** exception, which is a reference that has the name **Failure** in F# code. The following code illustrates the use of **failwith** to throw an exception.

[!CODE [FsLangRef2#6001](../CodeSnippet/VS_Snippets_Fsharp/fslangref2/FSharp/fs/failwith.fs#6001)]
    
## See Also
[Exception Handling &#40;F&#35;&#41;](Exception+Handling+%28F%23%29.md)

[Exception Types &#40;F&#35;&#41;](Exception+Types+%28F%23%29.md)

[Exceptions: The try...with Expression &#40;F&#35;&#41;](Exceptions%3A+The+try...with+Expression+%28F%23%29.md)

[Exceptions: The try...finally Expression &#40;F&#35;&#41;](Exceptions%3A+The+try...finally+Expression+%28F%23%29.md)

[Exceptions: the raise Function &#40;F&#35;&#41;](Exceptions%3A+the+raise+Function+%28F%23%29.md)

