# Exceptions: The failwith Function (F#)

The **failwith** function generates an F# exception.


## [!INCLUDE[System_CAPS_syntax](//System/Token/System_CAPS_syntax_md.md)]

```
failwith error-message-string
```

## [!INCLUDE[System_CAPS_remarks](//System/Token/System_CAPS_remarks_md.md)]
The *error-message-string* in the previous syntax is a literal string or a value of type **string**. It becomes the **Message** property of the exception.

The exception that is generated by **failwith** is a **Microsoft.FSharp.Core.FailureException** exception, which is a reference that has the name **Failure** in F# code. The following code illustrates the use of **failwith** to throw an exception.

[!CODE [FsLangRef2#6001](../CodeSnippet/VS_Snippets_Fsharp/fslangref2/FSharp/fs/failwith.fs#6001)]
    
## See Also
[Exception Handling &#40;F&#35;&#41;](Exception+Handling+28%F%2329%.md)

[Exception Types &#40;F&#35;&#41;](Exception+Types+28%F%2329%.md)

[Exceptions: The try...with Expression &#40;F&#35;&#41;](Exceptions%3A+The+try...with+Expression+28%F%2329%.md)

[Exceptions: The try...finally Expression &#40;F&#35;&#41;](Exceptions%3A+The+try...finally+Expression+28%F%2329%.md)

[Exceptions: the raise Function &#40;F&#35;&#41;](Exceptions%3A+the+raise+Function+28%F%2329%.md)

